# Gradle 配置属性

# Java 版本
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# 默认关闭非必要构建特性以加速构建
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.resvalues=false

# Gradle 并行构建
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
